/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppleAssnPostRequest,
  BookableResourceAvailability,
  CreateVenueRequest,
  Service,
  VenuePost201Response,
  VerifyTransactionPostRequest,
} from '../models/index';
import {
    AppleAssnPostRequestFromJSON,
    AppleAssnPostRequestToJSON,
    BookableResourceAvailabilityFromJSON,
    BookableResourceAvailabilityToJSON,
    CreateVenueRequestFromJSON,
    CreateVenueRequestToJSON,
    ServiceFromJSON,
    ServiceToJSON,
    VenuePost201ResponseFromJSON,
    VenuePost201ResponseToJSON,
    VerifyTransactionPostRequestFromJSON,
    VerifyTransactionPostRequestToJSON,
} from '../models/index';

export interface AppleAssnPostOperationRequest {
    appleAssnPostRequest: AppleAssnPostRequest;
}

export interface CreateVenuePostRequest {
    createVenueRequest: CreateVenueRequest;
}

export interface FlowsWhatsappCreateBookingPostRequest {
    body: object;
}

export interface FrequentservicesGetRequest {
    venueId: string;
}

export interface GetTimeSlotsGetRequest {
    venueId: string;
    serviceIds: Array<string>;
    date: Date;
}

export interface VenuePostRequest {
    createVenueRequest: CreateVenueRequest;
}

export interface VerifyTransactionPostOperationRequest {
    verifyTransactionPostRequest: VerifyTransactionPostRequest;
}

export interface WebhookWhatsappGetRequest {
    hubMode?: string;
    hubChallenge?: string;
    hubVerifyToken?: string;
}

export interface WebhookWhatsappPostRequest {
    body: object;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Handle App Store Server Notifications (ASSN)
     */
    async appleAssnPostRaw(requestParameters: AppleAssnPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['appleAssnPostRequest'] == null) {
            throw new runtime.RequiredError(
                'appleAssnPostRequest',
                'Required parameter "appleAssnPostRequest" was null or undefined when calling appleAssnPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/apple_assn`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppleAssnPostRequestToJSON(requestParameters['appleAssnPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handle App Store Server Notifications (ASSN)
     */
    async appleAssnPost(requestParameters: AppleAssnPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.appleAssnPostRaw(requestParameters, initOverrides);
    }

    /**
     * Create sample plans
     */
    async createPlansPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/create_plans`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create sample plans
     */
    async createPlansPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPlansPostRaw(initOverrides);
    }

    /**
     * Create venue (alias)
     */
    async createVenuePostRaw(requestParameters: CreateVenuePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenuePost201Response>> {
        if (requestParameters['createVenueRequest'] == null) {
            throw new runtime.RequiredError(
                'createVenueRequest',
                'Required parameter "createVenueRequest" was null or undefined when calling createVenuePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/create_venue`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVenueRequestToJSON(requestParameters['createVenueRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenuePost201ResponseFromJSON(jsonValue));
    }

    /**
     * Create venue (alias)
     */
    async createVenuePost(requestParameters: CreateVenuePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenuePost201Response> {
        const response = await this.createVenuePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * WhatsApp flow - create booking
     */
    async flowsWhatsappCreateBookingPostRaw(requestParameters: FlowsWhatsappCreateBookingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling flowsWhatsappCreateBookingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/flows/whatsapp/create_booking`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * WhatsApp flow - create booking
     */
    async flowsWhatsappCreateBookingPost(requestParameters: FlowsWhatsappCreateBookingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.flowsWhatsappCreateBookingPostRaw(requestParameters, initOverrides);
    }

    /**
     * Get frequently booked services
     */
    async frequentservicesGetRaw(requestParameters: FrequentservicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Service>>> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling frequentservicesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['venueId'] != null) {
            queryParameters['venue_id'] = requestParameters['venueId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/frequentservices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceFromJSON));
    }

    /**
     * Get frequently booked services
     */
    async frequentservicesGet(requestParameters: FrequentservicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Service>> {
        const response = await this.frequentservicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get available time slots (legacy)
     */
    async getTimeSlotsGetRaw(requestParameters: GetTimeSlotsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookableResourceAvailability>>> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling getTimeSlotsGet().'
            );
        }

        if (requestParameters['serviceIds'] == null) {
            throw new runtime.RequiredError(
                'serviceIds',
                'Required parameter "serviceIds" was null or undefined when calling getTimeSlotsGet().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling getTimeSlotsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['venueId'] != null) {
            queryParameters['venue_id'] = requestParameters['venueId'];
        }

        if (requestParameters['serviceIds'] != null) {
            queryParameters['service_ids'] = requestParameters['serviceIds'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = (requestParameters['date'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/get_time_slots`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookableResourceAvailabilityFromJSON));
    }

    /**
     * Get available time slots (legacy)
     */
    async getTimeSlotsGet(requestParameters: GetTimeSlotsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookableResourceAvailability>> {
        const response = await this.getTimeSlotsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get available time slots (legacy POST)
     */
    async getTimeSlotsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookableResourceAvailability>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/get_time_slots`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookableResourceAvailabilityFromJSON));
    }

    /**
     * Get available time slots (legacy POST)
     */
    async getTimeSlotsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookableResourceAvailability>> {
        const response = await this.getTimeSlotsPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Send test notification via App Store Server API
     */
    async sendTestNotificationPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/send_test_notification`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send test notification via App Store Server API
     */
    async sendTestNotificationPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendTestNotificationPostRaw(initOverrides);
    }

    /**
     * Create venue
     */
    async venuePostRaw(requestParameters: VenuePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenuePost201Response>> {
        if (requestParameters['createVenueRequest'] == null) {
            throw new runtime.RequiredError(
                'createVenueRequest',
                'Required parameter "createVenueRequest" was null or undefined when calling venuePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venue`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVenueRequestToJSON(requestParameters['createVenueRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenuePost201ResponseFromJSON(jsonValue));
    }

    /**
     * Create venue
     */
    async venuePost(requestParameters: VenuePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenuePost201Response> {
        const response = await this.venuePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify App Store transaction
     */
    async verifyTransactionPostRaw(requestParameters: VerifyTransactionPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['verifyTransactionPostRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyTransactionPostRequest',
                'Required parameter "verifyTransactionPostRequest" was null or undefined when calling verifyTransactionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/verify_transaction`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyTransactionPostRequestToJSON(requestParameters['verifyTransactionPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Verify App Store transaction
     */
    async verifyTransactionPost(requestParameters: VerifyTransactionPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.verifyTransactionPostRaw(requestParameters, initOverrides);
    }

    /**
     * WhatsApp webhook verification
     */
    async webhookWhatsappGetRaw(requestParameters: WebhookWhatsappGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['hubMode'] != null) {
            queryParameters['hub.mode'] = requestParameters['hubMode'];
        }

        if (requestParameters['hubChallenge'] != null) {
            queryParameters['hub.challenge'] = requestParameters['hubChallenge'];
        }

        if (requestParameters['hubVerifyToken'] != null) {
            queryParameters['hub.verify_token'] = requestParameters['hubVerifyToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/webhook/whatsapp`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * WhatsApp webhook verification
     */
    async webhookWhatsappGet(requestParameters: WebhookWhatsappGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.webhookWhatsappGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * WhatsApp webhook receiver
     */
    async webhookWhatsappPostRaw(requestParameters: WebhookWhatsappPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling webhookWhatsappPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/webhook/whatsapp`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * WhatsApp webhook receiver
     */
    async webhookWhatsappPost(requestParameters: WebhookWhatsappPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhookWhatsappPostRaw(requestParameters, initOverrides);
    }

}
