/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppleAssnPostRequest
 */
export interface AppleAssnPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AppleAssnPostRequest
     */
    signedPayload: string;
}

/**
 * Check if a given object implements the AppleAssnPostRequest interface.
 */
export function instanceOfAppleAssnPostRequest(value: object): value is AppleAssnPostRequest {
    if (!('signedPayload' in value) || value['signedPayload'] === undefined) return false;
    return true;
}

export function AppleAssnPostRequestFromJSON(json: any): AppleAssnPostRequest {
    return AppleAssnPostRequestFromJSONTyped(json, false);
}

export function AppleAssnPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppleAssnPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'signedPayload': json['signedPayload'],
    };
}

export function AppleAssnPostRequestToJSON(json: any): AppleAssnPostRequest {
    return AppleAssnPostRequestToJSONTyped(json, false);
}

export function AppleAssnPostRequestToJSONTyped(value?: AppleAssnPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signedPayload': value['signedPayload'],
    };
}

