/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReservationRequest
 */
export interface CreateReservationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    venueId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    staffId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    bookingResourceName: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateReservationRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateReservationRequest
     */
    endDate: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateReservationRequest
     */
    serviceIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    guestId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    guestName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    guestNotes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationRequest
     */
    eventId?: string | null;
}

/**
 * Check if a given object implements the CreateReservationRequest interface.
 */
export function instanceOfCreateReservationRequest(value: object): value is CreateReservationRequest {
    if (!('venueId' in value) || value['venueId'] === undefined) return false;
    if (!('staffId' in value) || value['staffId'] === undefined) return false;
    if (!('bookingResourceName' in value) || value['bookingResourceName'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('serviceIds' in value) || value['serviceIds'] === undefined) return false;
    return true;
}

export function CreateReservationRequestFromJSON(json: any): CreateReservationRequest {
    return CreateReservationRequestFromJSONTyped(json, false);
}

export function CreateReservationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReservationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'venueId': json['venue_id'],
        'staffId': json['staff_id'],
        'bookingResourceName': json['booking_resource_name'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'serviceIds': json['service_ids'],
        'status': json['status'] == null ? undefined : json['status'],
        'guestId': json['guest_id'] == null ? undefined : json['guest_id'],
        'guestName': json['guest_name'] == null ? undefined : json['guest_name'],
        'guestNotes': json['guest_notes'] == null ? undefined : json['guest_notes'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
    };
}

export function CreateReservationRequestToJSON(json: any): CreateReservationRequest {
    return CreateReservationRequestToJSONTyped(json, false);
}

export function CreateReservationRequestToJSONTyped(value?: CreateReservationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'venue_id': value['venueId'],
        'staff_id': value['staffId'],
        'booking_resource_name': value['bookingResourceName'],
        'start_date': ((value['startDate']).toISOString()),
        'end_date': ((value['endDate']).toISOString()),
        'service_ids': value['serviceIds'],
        'status': value['status'],
        'guest_id': value['guestId'],
        'guest_name': value['guestName'],
        'guest_notes': value['guestNotes'],
        'event_id': value['eventId'],
    };
}

