/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateVenueRequest
 */
export interface CreateVenueRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateVenueRequest
     */
    organisationName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVenueRequest
     */
    timezoneId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVenueRequest
     */
    userId?: string | null;
}

/**
 * Check if a given object implements the CreateVenueRequest interface.
 */
export function instanceOfCreateVenueRequest(value: object): value is CreateVenueRequest {
    if (!('organisationName' in value) || value['organisationName'] === undefined) return false;
    if (!('timezoneId' in value) || value['timezoneId'] === undefined) return false;
    return true;
}

export function CreateVenueRequestFromJSON(json: any): CreateVenueRequest {
    return CreateVenueRequestFromJSONTyped(json, false);
}

export function CreateVenueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVenueRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organisationName': json['organisationName'],
        'timezoneId': json['timezoneId'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function CreateVenueRequestToJSON(json: any): CreateVenueRequest {
    return CreateVenueRequestToJSONTyped(json, false);
}

export function CreateVenueRequestToJSONTyped(value?: CreateVenueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisationName': value['organisationName'],
        'timezoneId': value['timezoneId'],
        'user_id': value['userId'],
    };
}

