/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReservationResponse
 */
export interface CreateReservationResponse {
    /**
     * Unique identifier for the created reservation
     * @type {string}
     * @memberof CreateReservationResponse
     */
    reservationId: string;
}

/**
 * Check if a given object implements the CreateReservationResponse interface.
 */
export function instanceOfCreateReservationResponse(value: object): value is CreateReservationResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    return true;
}

export function CreateReservationResponseFromJSON(json: any): CreateReservationResponse {
    return CreateReservationResponseFromJSONTyped(json, false);
}

export function CreateReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReservationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reservationId': json['reservation_id'],
    };
}

export function CreateReservationResponseToJSON(json: any): CreateReservationResponse {
    return CreateReservationResponseToJSONTyped(json, false);
}

export function CreateReservationResponseToJSONTyped(value?: CreateReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reservation_id': value['reservationId'],
    };
}

