/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReservationPost201Response
 */
export interface ReservationPost201Response {
    /**
     * 
     * @type {string}
     * @memberof ReservationPost201Response
     */
    reservationId: string;
}

/**
 * Check if a given object implements the ReservationPost201Response interface.
 */
export function instanceOfReservationPost201Response(value: object): value is ReservationPost201Response {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    return true;
}

export function ReservationPost201ResponseFromJSON(json: any): ReservationPost201Response {
    return ReservationPost201ResponseFromJSONTyped(json, false);
}

export function ReservationPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'reservationId': json['reservation_id'],
    };
}

export function ReservationPost201ResponseToJSON(json: any): ReservationPost201Response {
    return ReservationPost201ResponseToJSONTyped(json, false);
}

export function ReservationPost201ResponseToJSONTyped(value?: ReservationPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reservation_id': value['reservationId'],
    };
}

