/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Service
 */
export interface Service {
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Service
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof Service
     */
    durationInMinutes: number;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    gender: string;
    /**
     * 
     * @type {boolean}
     * @memberof Service
     */
    isFrequentlyBooked: boolean;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    parentService: string;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    title: string;
}

/**
 * Check if a given object implements the Service interface.
 */
export function instanceOfService(value: object): value is Service {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('durationInMinutes' in value) || value['durationInMinutes'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('isFrequentlyBooked' in value) || value['isFrequentlyBooked'] === undefined) return false;
    if (!('parentService' in value) || value['parentService'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ServiceFromJSON(json: any): Service {
    return ServiceFromJSONTyped(json, false);
}

export function ServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Service {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'amount': json['amount'],
        'durationInMinutes': json['durationInMinutes'],
        'gender': json['gender'],
        'isFrequentlyBooked': json['isFrequentlyBooked'],
        'parentService': json['parent_service'],
        'title': json['title'],
    };
}

export function ServiceToJSON(json: any): Service {
    return ServiceToJSONTyped(json, false);
}

export function ServiceToJSONTyped(value?: Service | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'durationInMinutes': value['durationInMinutes'],
        'gender': value['gender'],
        'isFrequentlyBooked': value['isFrequentlyBooked'],
        'parent_service': value['parentService'],
        'title': value['title'],
    };
}

