/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    analytics: boolean;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    maxGuests: number;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    maxReservations: number;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    maxStylists: number;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    planId: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    planName: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    status: string;
}

/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('analytics' in value) || value['analytics'] === undefined) return false;
    if (!('maxGuests' in value) || value['maxGuests'] === undefined) return false;
    if (!('maxReservations' in value) || value['maxReservations'] === undefined) return false;
    if (!('maxStylists' in value) || value['maxStylists'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('planName' in value) || value['planName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {
        
        'analytics': json['analytics'],
        'maxGuests': json['max_guests'],
        'maxReservations': json['max_reservations'],
        'maxStylists': json['max_stylists'],
        'planId': json['plan_id'],
        'planName': json['plan_name'],
        'status': json['status'],
    };
}

export function SubscriptionToJSON(json: any): Subscription {
    return SubscriptionToJSONTyped(json, false);
}

export function SubscriptionToJSONTyped(value?: Subscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analytics': value['analytics'],
        'max_guests': value['maxGuests'],
        'max_reservations': value['maxReservations'],
        'max_stylists': value['maxStylists'],
        'plan_id': value['planId'],
        'plan_name': value['planName'],
        'status': value['status'],
    };
}

