/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Usage
 */
export interface Usage {
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    guests: number;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    reservations: number;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    services: number;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    stylists: number;
}

/**
 * Check if a given object implements the Usage interface.
 */
export function instanceOfUsage(value: object): value is Usage {
    if (!('guests' in value) || value['guests'] === undefined) return false;
    if (!('reservations' in value) || value['reservations'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    if (!('stylists' in value) || value['stylists'] === undefined) return false;
    return true;
}

export function UsageFromJSON(json: any): Usage {
    return UsageFromJSONTyped(json, false);
}

export function UsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usage {
    if (json == null) {
        return json;
    }
    return {
        
        'guests': json['guests'],
        'reservations': json['reservations'],
        'services': json['services'],
        'stylists': json['stylists'],
    };
}

export function UsageToJSON(json: any): Usage {
    return UsageToJSONTyped(json, false);
}

export function UsageToJSONTyped(value?: Usage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guests': value['guests'],
        'reservations': value['reservations'],
        'services': value['services'],
        'stylists': value['stylists'],
    };
}

