/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenuePost201Response
 */
export interface VenuePost201Response {
    /**
     * 
     * @type {string}
     * @memberof VenuePost201Response
     */
    venueId: string;
}

/**
 * Check if a given object implements the VenuePost201Response interface.
 */
export function instanceOfVenuePost201Response(value: object): value is VenuePost201Response {
    if (!('venueId' in value) || value['venueId'] === undefined) return false;
    return true;
}

export function VenuePost201ResponseFromJSON(json: any): VenuePost201Response {
    return VenuePost201ResponseFromJSONTyped(json, false);
}

export function VenuePost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenuePost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'venueId': json['venueId'],
    };
}

export function VenuePost201ResponseToJSON(json: any): VenuePost201Response {
    return VenuePost201ResponseToJSONTyped(json, false);
}

export function VenuePost201ResponseToJSONTyped(value?: VenuePost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'venueId': value['venueId'],
    };
}

