/* tslint:disable */
/* eslint-disable */
/**
 * Firefly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyTransactionPostRequest
 */
export interface VerifyTransactionPostRequest {
    /**
     * JWS transaction
     * @type {string}
     * @memberof VerifyTransactionPostRequest
     */
    transaction: string;
}

/**
 * Check if a given object implements the VerifyTransactionPostRequest interface.
 */
export function instanceOfVerifyTransactionPostRequest(value: object): value is VerifyTransactionPostRequest {
    if (!('transaction' in value) || value['transaction'] === undefined) return false;
    return true;
}

export function VerifyTransactionPostRequestFromJSON(json: any): VerifyTransactionPostRequest {
    return VerifyTransactionPostRequestFromJSONTyped(json, false);
}

export function VerifyTransactionPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyTransactionPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': json['transaction'],
    };
}

export function VerifyTransactionPostRequestToJSON(json: any): VerifyTransactionPostRequest {
    return VerifyTransactionPostRequestToJSONTyped(json, false);
}

export function VerifyTransactionPostRequestToJSONTyped(value?: VerifyTransactionPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction': value['transaction'],
    };
}

